### ISSUE TITLE
Investigate eval_in_caller problem

### ISSUE THREAD

**Issue by markburns** [ruby-analysis/delfos#16]
Evaluating `{self: is_a?(Module)}` vs `is_a(Module)` results in different values of `is_a?(Module)`
With unfortunately, the correct value being in the former one.

https://github.com/ruby-analysis/delfos/blob/5ab6a0219e2e1e7677750c1b2b0dfe974f727f2c/lib/delfos/method_trace/container_method.rb#L50

I have no idea why this is the case at the moment, but would like to find out.

Perhaps our tests pass by coincidence, and the actual value of `is_a?(Module)` ends up coming from the wrong height in the call stack.

We could try and add in some unit tests to the `EvalInCaller` module with various combinations of class/instance methods calling instance/class methods and vice versa and check that we always get the correct value for whether the caller is a Module. 

Maybe there is a difference between different ways of defining a class method?

```ruby
class MyClass
  def self.option_1
  end

  class << self
    def option_2
    end
  end
end

def MyClass.option_3
end
```

**Comment by muzfuz** [comment]
I suspect this one will require a bit of a deep dive, will come at this once the fix from https://github.com/ruby-analysis/delfos/pull/18 is in.

**Comment by markburns** [comment]
![image](https://user-images.githubusercontent.com/104158/27213813-1224af12-52a4-11e7-9fbc-7e494a6d1ad7.png)
