### ISSUE TITLE
Make paths consistent when code called from (main)

### ISSUE THREAD

**Issue by markburns** [ruby-analysis/delfos#20]
See here: https://github.com/ruby-analysis/delfos/blob/efb66d5a8327a3517bb4c73d49ddf0007a2e3c08/spec/integration/app_lib_app_spec.rb#L34

**Comment by muzfuz** [comment]
Hm... how odd.

**Comment by markburns** [comment]
This is slightly tricky because we ideally want just the relative path within e.g. app or lib to be persisted but in other cases the full path is used to determine whether we should log it.
The concepts of filename and path are used somewhat interchangeably in the project. It might be nice to have a better more consistent and easy to understand convention that covers both use cases clearly

**Comment by markburns** [comment]
I want to use the following convention

Assuming 
```ruby
Delfos.application_directories = ["app", "lib"]`

# app/models/admin/users_controller.rb
class Admin::UsersController
end

# lib/third_party/setup.rb
module ThirdParty::Setup
end
```
 in `/Users/mark/code/some_rails_app`

Then for the app file
* `path` is `"app/models/admin/users_controller.rb"`
* `relative_path` is `"models/admin/users_controller.rb"`
* `full_path` is `"/Users/mark/code/some_rails_app/app/models/admin/users_controller.rb"`

For the lib file.
* `path` is `"lib/third_party/setup.rb"`
* `relative_path` is `"third_party/setup.rb"`
* `full_path` is `"/Users/mark/code/some_rails_app/lib/third_party/setup.rb"`

Where
* `path` is persisted in neo4j, 
* `full_path` may be used for file system comparisons. E.g. to determine when/if to log
* `relative_path` - I am not 100% if we need this, but I seem to remember some reason for it.

Issues might arise where we have multiple apps with the same nested path underneath both `app` and `lib`

**Comment by markburns** [comment]
Fixed underlying issue in https://github.com/ruby-analysis/delfos/blob/75478c0eb6b32f6f9e890e0facb0de28124bcfe5/lib/delfos/method_trace/code_location/container_method_factory.rb - although not addressed the last comment in this issue
