### ISSUE TITLE
Modules that do a class_eval inside self.included methods seem to cause confusion.

### ISSUE THREAD

**Issue by muzfuz** [ruby-analysis/delfos#23]
Given the following example:

```ruby
module ProductAttributes
  def self.included(klass)
    klass.class_eval do
      attr_accessor :price
    end
  end
end

class Product
  include ProductAttributes

  def initialize(price)
    @price = price
  end
end
```

The Neo4j call site logger throws up the following error message:

```
~/delfos/lib/delfos/neo4j/query_execution/transactional.rb:57:in `validate!':
 {"code"=>"Neo.ClientError.Statement.SemanticError", "message"=>"Cannot merge node using null property value for line_number"}
(Delfos::Neo4j::QueryExecution::InvalidQuery)
```

I've started investigating but it's a bit hard to figure out where this problem is originating.

**Comment by muzfuz** [comment]
Here's the accompanying stacktrace

```
from ~/delfos/lib/delfos/neo4j/query_execution/transactional.rb:35:in `perform'
from ~/delfos/lib/delfos/neo4j/batch/execution.rb:36:in `perform_query'
from ~/delfos/lib/delfos/neo4j/batch/execution.rb:20:in `execute!'
from ~/delfos/lib/delfos/neo4j/batch/retryable.rb:38:in `block in execute!'
from ~/delfos/lib/delfos/neo4j/batch/retryable.rb:52:in `with_retry'
from ~/delfos/lib/delfos/neo4j/batch/retryable.rb:37:in `execute!'
from ~/delfos/lib/delfos/neo4j/batch/retryable.rb:11:in `execute!'
from ~/delfos/lib/delfos/neo4j.rb:18:in `execute'
from ~/delfos/lib/delfos/neo4j/call_site_logger.rb:22:in `perform'
from ~/delfos/lib/delfos/neo4j/call_site_logger.rb:10:in `save_call_stack'
from ~/delfos/lib/delfos/call_stack.rb:39:in `save!'
from ~/delfos/lib/delfos/call_stack/stack.rb:24:in `call'
from ~/delfos/lib/delfos/call_stack/stack.rb:24:in `pop'
from ~/delfos/lib/delfos/call_stack.rb:27:in `pop'
from ~/delfos/lib/delfos/method_trace.rb:34:in `block in on_return'
from ~/delfos/lib/delfos/method_trace.rb:53:in `block in setup_trace_point'
from ~/Desktop/testapp/lib/testapp/product.rb:2:in `included'
from ~/Desktop/testapp/lib/testapp/product.rb:10:in `include'
from ~/Desktop/testapp/lib/testapp/product.rb:10:in `<class:Product>'
from ~/Desktop/testapp/lib/testapp/product.rb:9:in `<top (required)>'
from ~/Desktop/testapp/lib/testapp.rb:8:in `require'
from ~/Desktop/testapp/lib/testapp.rb:8:in `<top (required)>'
```

**Comment by muzfuz** [comment]
Looks to me like we're having trouble determining file / call site information:

```
{:params=>"{\"file0\"=>\"lib/deltest/product.rb\", \"line_number0\"=>10, \"execution_count0\"=>1, \"step_number0\"=>1, \"klass0\"=>\"Product\", \"method_name0\"=>\"(main)\", \"method_type0\"=>\"ClassMethod\", \"method_definition_line0\"=>nil}"}
```

**Comment by markburns** [comment]
Ah interesting. So this must be in the container method factory. Should
maybe be able to write a test copying one of the recently added ones.
It's a bit tricky because you need to set the stack offset to match the
example and I had to do it inside the fixture too.

**Comment by markburns** [comment]
FYI - This doesn't happen on neo4j 2.x.

**Comment by muzfuz** [comment]
Interesting.  I did wonder if we shouldn't just ignore nil values if they arise.

**Comment by markburns** [comment]
Yeah maybe. Although It feels quite error prone to ignore.
If it's just the container method line number that proves difficult to get, then there is still value having the rest of the info recorded.
So I might allow that specific use case to go through.

But first I am trying to fix the underlying issue and fetch the line number correctly.
There may be some interplay of a few issues.

Firstly the `attr_accessor` calls are probably recorded in `:c_call` tracepoints. Although it doesn't look like we are getting that far or even calling the accessor, so not relevant to this example.

Secondly, dealing with determining the container method name with the specific metaprogramming in your example.

Thirdly, `.included` is defined in ruby, but is called from C. This means we end up popping the stack when the `:return` TracePoint is triggered but it was never added to the stack with `:c_call`

It's tempting to just allow `nil` values for `ContainerMethod#line_number`s.

**Comment by markburns** [comment]
I guess another thing to bear in mind is recording this type of method call I.e. the `Module.include` method calls, is probably not all that valuable in terms of the goals for this project.
It's just setup stuff that happens at load time and not really application logic that happens at runtime.

**Comment by muzfuz** [comment]
Totally agree with your last point - really we are more interested in methods that are called on objects and not necessarily if they live on certain modules or not.  (Depending on use case).
