### ISSUE TITLE
Fix missing line numbers in container_method

### ISSUE THREAD

**Issue by markburns** [ruby-analysis/delfos#25]
See #23 

https://github.com/ruby-analysis/delfos/issues/23#issuecomment-308925291

I've deployed a workaround to ignore cases where we have missing `container_method.line_number`s. Which seem to occur during 'compile time' loading of modules (rather than runtime execution). So it's not as critical for tracking valuable coupling information.

It would be nice to have a more thorough solution that enables tracking of pushing onto the call stack via `:call` and popping off via `:c_call` `TracePoint` events where appropriate.

**Comment by markburns** [comment]
@muzfuz - Hey apologies - this workaround was temporarily not on master after unifying the queries. 

Although, I believe the original issue is now fixed with the further simplification done in 

https://github.com/ruby-analysis/delfos/blob/75478c0eb6b32f6f9e890e0facb0de28124bcfe5/lib/delfos/method_trace/code_location/container_method_factory.rb

I'll get a build against neo4j v3.x up and running too on CI and maybe look at supporting a few ruby versions at the same time

**Comment by muzfuz** [comment]
@markburns no probs.  I've just about got things ticking along at this end, so I'll be able to refocus on this stuff in the coming days.
