### ISSUE TITLE
Outdated stubs/mocks elimination as possible sphere of application

### ISSUE THREAD

**Issue by MitinPavel** [ruby-analysis/delfos#3]
It is not a regular github issue. It is a question.

Have you considered mock and stub checking in test environment as a possible application area for the gem?

There is a well known problem with mocked/stubbed automated tests. The problem is especially manifested in languages without static typing. If an interface of a collaborator is changed, stubbed tests continue to be green since mocks/stubs know nothing about the changes.
```
class MyCollaborator
  def perform
     # ommited ...
  end
end

# Test
collaborator = mock(:perform => nil)
MySUT.new(collaborator).do_something
```
Now if MyCollaborator#perform is renamed to #process, the test remains green.

Would it be hard to use `delfos` for periodic codebase chekcing? Running it from time to time against:
1) tests with stubbed/mocked collaborator
2) regular tests for collaborator itself OR actual production environment

Having the two data-sets, it would be possible to compare them and find outdated mocks.

**Comment by markburns** [comment]
Hey Mitin, thanks for the reminder. I'm currently working on
batching/streaming of the queries, then will look at this.
Would you be able to get together a small test case? Maybe one that uses
the same versions of gems you use on the project you mentioned?
You could do as a PR here into an examples directory. Then I should be able
to easily show you queries and write a simple rake task that detects the
issue.

**Comment by markburns** [comment]
Feel free to re-open if you get a chance to add an example.
Sorry, not had time to try setting one up myself.
